name: apis
description: "This package serves as the API network layer for e-commerce applications. It provides RESTful API handling for Shopify and WooCommerce, with a modern wizard-based configuration system and cross-platform storage (SQLite3 for mobile, SharedPreferences for web)."

version: 0.0.1
# homepage:

# Environment configuration
environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

# -------------------------------
# Regular dependencies
# -------------------------------
dependencies:
  # Flutter SDK dependency
  flutter:
    sdk: flutter

  # Dependency injection
  injectable: 2.5.0
  get_it: 7.7.0

  # Networking
  retrofit: 4.1.0
  dio: 5.4.3+1
  dio_cookie_manager: 2.1.4

  # File management
  path_provider: 2.1.5

  # Database and Storage
  sqflite: ^2.4.2
  path: ^1.9.0
  shared_preferences: ^2.5.3

  # Logging
  logger: 1.4.0

  # Code generation and annotations
  json_annotation: ^4.8.1
  freezed_annotation: 2.4.4
  freezed: 2.5.7
  
  # GraphQL dependencies
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2

# -------------------------------
# Development dependencies
# -------------------------------
dev_dependencies:
  # Flutter testing framework
  flutter_test:
    sdk: flutter

  # Linting rules
  flutter_lints: 2.0.3

  # Code generation tools
  build_runner: 2.4.13
  injectable_generator: 2.6.2
  json_serializable: ^6.7.1
  retrofit_generator: 8.1.2
  
  # GraphQL code generation
  graphql_codegen: ^1.1.1

