// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIMt2LCKGo_h3mcqqIcP5DRUPQS3ovHPI',
    appId: '1:384773402210:web:7e909e95a35b69eaba2b3b',
    messagingSenderId: '384773402210',
    projectId: 'osmea-app',
    authDomain: 'osmea-app.firebaseapp.com',
    storageBucket: 'osmea-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeBekpGafebXEM4Okq6bu15Xm4i9lctPw',
    appId: '1:384773402210:android:963fd6d251b71069ba2b3b',
    messagingSenderId: '384773402210',
    projectId: 'osmea-app',
    storageBucket: 'osmea-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC47INjr-dj_FNeUphDSYP_p1zXzN_WE04',
    appId: '1:384773402210:ios:ee1ed354ca8b3d8bba2b3b',
    messagingSenderId: '384773402210',
    projectId: 'osmea-app',
    storageBucket: 'osmea-app.firebasestorage.app',
    iosBundleId: 'com.osmea.core',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC47INjr-dj_FNeUphDSYP_p1zXzN_WE04',
    appId: '1:384773402210:ios:ee1ed354ca8b3d8bba2b3b',
    messagingSenderId: '384773402210',
    projectId: 'osmea-app',
    storageBucket: 'osmea-app.firebasestorage.app',
    iosBundleId: 'com.osmea.core',
  );
}
