name: osmea_components
description: OSMEA UI Kit for e-commerce applications with design tokens system
version: 0.1.0
homepage: https://github.com/masterfabric-mobile/osmea

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Add any assets or fonts your package needs here
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf

